# Please make sure to update the license_key information with the
# license key for your New Relic account.
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: '268de3a2041f213b55a4cc2df59d97f0ff9d8b7a'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# AWS configuration.
#
aws:
  # Update with you AWS account keys:
  access_key: 'AKIAJHQDWCQVYHKXZMSA'
  secret_key: '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'
  # Specify AWS regions to query for metrics
  regions:
    #ap-northeast-1
    us-east-1
#
# Agent configuration.
#
agents:
  #
  # Uncomment an agent to enable it. Set 'overview' to true to
  # enable its overview plugin (eg. EC2 Overview), displaying all
  # metrics on a single dashboard (currently only available for EC2 & EBS).
  #
  swf:
   overview: true
  #ec2:
  # overview: true
  #ebs:
  # overview: true
  #elb:
  #  overview: false
  #rds:
  #  overview: false
  #sqs:
  #  overview: false
  #sns:
  #  overview: false
  #ec:
  #  overview: false
